= Lim Ming Hong - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: CorpPro

---

== Overview

CorpPro is a desktop address book application which targets small to medium corporates and allow their workers to keep track of colleague information in the office.
CorpPro allows users to `add`, `edit` and `tag` with the Command Line Interface (CLI) or the Graphical User Interface (GUI) that is created with JavaFX.
This portfolio contains the contributions i had made towards the improvement of the basic Address Book provided to us. +

== Summary of contributions

* *Major enhancement 1*: added *the ability to export and import your contacts information.*
** What it does: Allows the user export contacts to a CSV file in any existing directory. Vice versa, CSV files can also be imported from any existing directory and be appended to the address book.
** Justification: Changing systems will be much easier as contact information can be packaged into an
easy to read format and exchanged between systems.
** Highlights: In order to ensure that the exported file can be read by other applications, CorpPro have to write the file in a way that it can be easily adapted by the other spreadsheet applications. +
When files are imported from other applications, in depth analysis have to be made to ensure that it can read the format of the file formatted by these spreadsheet applications.

* *Major enhancement 2*: added *the ability to back up and restore your address book.*
** What it does: Allow the user to back up their address book at any point in time. This allows them to revert their address book to any previous state if they wish to.
** Justification: This feature allows the user to retrieve any lost information if they have accidentally deleted any.
** Highlights: Careful planning has to be done as saving the folders in a separate directory will result in the database being easily accessible. Therefore, we have to protect the folder the backups are saved by making the directory unknown.

* *Code contributed*: [https://nuscs2113-ay1819s1.github.io/dashboard/#=undefined&search=limminghong[RepoSense]] [https://github.com/CS2113-AY1819S1-W12-3/main/pulls?q=is%3Apr+is%3Aclosed+author%3ALimminghong[Pull Requests]]

* *Other contributions*:

** Project management:
*** Managed releases `v1.1` - `v1.4` (4 releases) on GitHub
** Enhancements to existing features:
*** Wrote additional tests for existing features to increase coverage from 71% to 86% (Pull requests https://github.com/CS2113-AY1819S1-W12-3/main/pull/123[#123], https://github.com/CS2113-AY1819S1-W12-3/main/pull/158[#158])
*** Issues resolved [https://github.com/CS2113-AY1819S1-W12-3/main/issues?q=is%3Aissue+author%3ALimminghong+is%3Aclosed[Issues]]
** Documentation:
*** Did cosmetic tweaks to existing contents of the User Guide: https://github.com/CS2113-AY1819S1-W12-3/main/pull/158[#158]
** Community:
*** PRs reviewed (with non-trivial review comments): https://github.com/CS2113-AY1819S1-W12-3/main/pull/73[#17]
*** Reported bugs and suggestions for other teams in the class

== Contributions to the User Guide

|===
|_Given below are sections I contributed to the User Guide. I have added the description of all the features i have implemented and added a appendix which helps the user to understand how a CSV file works._
|===

include::../UserGuide.adoc[tag=backuprestore]

include::../UserGuide.adoc[tag=exportimport]

include::../UserGuide.adoc[tag=appendixA]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. I have written on the logic behind on how I have implemented the features that were tasked to me. It also showcases my  ability to draw sequence diagrams._
|===

include::../DeveloperGuide.adoc[tag=backuprestore]

include::../DeveloperGuide.adoc[tag=exportimport]
