= Ler Wei Sheng - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: CorpPro

---

== Overview
CorpPro is an address book for corporate users. +
It provides a fast and efficient system for corporate users to store their contacts safely and securely. It is also easy to maneuver and access contacts.
CorpPro is powered by JavaFX and boasts an intuitive GUI (Graphical User Interface) with easy-to-use CLI (Command Line Interface). +
This portfolio documents my ability to write java programs, as well as documentation in the form of user and developer guides.

== Summary of contributions

* *Feature 1*: Added the ability for users to secure their address book by *encrypting* data.
** What it does: Upon entering the `password` command followed by a password, it will encrypt the address book data using `PBEWithMD5AndDES` cipher.
** Justification: This feature was implemented so that corporate users can secure sensitive information in accordance to PDPA (Personal Data Protection Act) rules. This reduces the possibilities of data leaks and unwanted access.
** Highlights: This feature implements a well-known cipher `PBEWithMD5AndDES` and `PBEKeySpec` which accepts the user's password. Once the file is encrypted, it will not be crackable unless done via brute forcing.
It also requires file type checking to make sure that the user can compress both encryption and decryption process into one single `password` command much like a toggle so that users need not utilise 2 different commands for encrypting and decrypting.
** Credits: Code snippet adapted from Esailija [https://stackoverflow.com/questions/13673556/using-password-based-encryption-on-a-file-in-java[Stack overflow]]

* *Feature 2*: Implemented smart searching for `find` command.
** What it does: Users can now search for the contacts they want by approximately specifying other traits/ attributes of the contacts. For example, users can
search for contacts who live in Jurong West and are tagged as friends.
** Justification: Corporate users might need to gather rough statistics of their clients or know which worker(s) to contact and assign work.
** Highlights: This feature uses Levenshtein and Hamming Distance to find the closest match for the keywords entered. It will then sort the matches based on how close it is to the keywords entered.
After which, it will perform a *set intersection* on the search results to narrow it down before displaying it to the user.

* *Feature 3*: Implemented custom paths for data storage.
** What it does: Users can now specify the path they wish to save their addressbook.xml to.
** Justification: Corporate users might want to have separate address books without the need of storing their application in different folders.
They can instead edit the preference file to change the name and location of their data storage file path.
** Highlights: This feature requires implementing the json reader in `UserPrefs` class and storing it as a public variable for other classes to depend on.

* *Code contributed*: [https://github.com/CS2113-AY1819S1-W12-3/main/blob/master/collated/functional/lws803.md[Functional code]] [https://github.com/CS2113-AY1819S1-W12-3/main/blob/master/collated/test/lws803.md[Test code]]

* *Other contributions*:

** Project management:
*** Managed releases `v1.1` - `v2.0` (5 releases) on GitHub
** Documentation:
*** Did cosmetic tweaks to existing contents of the User Guide
** Community:
*** https://github.com/CS2113-AY1819S1-W12-3/main/pulls?q=is%3Apr+assignee%3Alws803+author%3Alws803+is%3Aclosed[PRs made]
*** https://github.com/CS2113-AY1819S1-W12-3/main/issues?q=is%3Aissue+is%3Aclosed+author%3Alws803[Reported bugs and suggestions for other teams in the class]
** Tools:
*** Integrated a new Github plugin (Travis ci) to the team repo
*** Integrated a new Github plugin (AppVeyor) to the team repo
*** Integrated a new Github plugin (Coverall) to the team repo

== Contributions to the User Guide

|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=search]

include::../UserGuide.adoc[tag=dataencryption]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=search]

include::../DeveloperGuide.adoc[tag=dataencryption]


